### ISSUE TITLE
obsremotejava 1.0.9-snapshot-increased-message-size-1 Dependency?

### ISSUE THREAD

**Issue by cbrews** [sampie777/obs-scene-que#3]
Hey--

I'm testing building this repo today but got a bit stuck on this dependency:
```
net.twasi.obsremotejava:1.0.9-snapshot-increased-message-size-1
```

I couldn't find this version of the websocket dependency here:
https://mvnrepository.com/artifact/net.twasi/obs-websocket-java

I was able to successfully rollback the version to 1.0.5 but had to disable a bunch of logic of related to these two classes:
* `net.twasi.obsremotejava.requests.GetSceneItemProperties.GetSceneItemPropertiesResponse`
* `net.twasi.obsremotejava.OBSRemoteController`

Is this 1.0.9-snapshot-increased-message-size-1 a custom version built by you?  Or is this in another repository somewhere that I'm missing.

Let me know--I'm trying to get this running on the latest version so I can do some testing with the queue sequencer.

Thanks,
Chris

**Comment by sampie777** [comment]
Hi @cbrews ,

I was wondering when someone would run into that problem. That 'missing' dependency is actually just a custom build of the 'websocket-obs-java' repository. Because I was changing so much code of that repository, I thought it might be inhumane to create a pull request to the master. 

You can download and build (```mvn install```) the custom branch here: [https://github.com/sampie777/websocket-obs-java/tree/increased-message-size-1](https://github.com/sampie777/websocket-obs-java/tree/increased-message-size-1)

**Comment by cbrews** [comment]
Thanks @sampie777 !

Sorry for the delay in getting back to you.  This resolved my issue and unblocked me.  I appreciate the detailed response.  I should be able to proceed from here onto next steps!
